database_manager:
  event ext: .xml
  event format: QUAKEML
  event path: GeoNet_database
  lookup starttime: 2010:01:01T00:00:00.00000Z
  min stations: 5
  name structure: '{event_id_end}'
  path structure: '{year}/{month}/{event_id_end}'
log_formatter: "%(asctime)s\t[%(processName)s:%(threadName)s]: %(name)s\t%(levelname)s\t%(message)s"
log_level: INFO
plot:
  highcut: 10.0
  lowcut: 1.0
  plot length: 600.0
notifier:
  service: "pushover"
    #user: "USER"
    #token: "TOKEN"
  user: "urh7q1ooa54nr1ioy9hf1ej1gs55ku"
  token: "acdb1qrxn7axpsr8aev4tbjnzv4u3t"
reactor:
  catalog lookup kwargs:
    maxlatitude: -34.52
    maxlongitude: -174.73
    minlatitude: -48.83
    minlongitude: 163.56
  magnitude threshold: 5.5
  max run length: null
  minimum events in bin: 10
  minimum lookup radius: 25.0
  rate radius: 0.2
  rate threshold: 100.0
  scaling multiplier: 2.0
  scaling relation: wells_coppersmith_subsurface
rt_match_filter:
  client: https://service.geonet.org.nz
  client type: FDSN
  detect interval: 60.0
  backfill interval: 300.0
  hypocentral separation: 30.0
  max correlation cores: 10
  max distance: 1000.0
  max run length: null
  min stations: 5
  minimum rate: 10
  n stations: 15
  plot: false
  plot detections: false
  save waveforms: false
  threshold: 9
  threshold type: MAD
  trig int: 2.0
  waveform client: https://service.geonet.org.nz
  waveform client type: FDSN
  local wave bank: null
streaming:
  buffer capacity: 600.0
  rt client type: seedlink
  rt client url: link.geonet.org.nz
template:
  filt order: 4
  highcut: 15.0
  length: 4.0
  lowcut: 2.0
  min snr: 2.0
  prepick: 0.2
  process len: 300
  samp rate: 50.0
  swin: all
plugins:
  order:
    - picker
    - hyp
    - nll
    - growclust
    - outputter
    - plotter
  plotter:
    sleep_interval: 240
  outputter:
    sleep_interval: 300
    output_templates: true
    retain_history: false
  picker:
    all horiz: false
    all vert: false
    cc dir: null
    cores: 1
    export cc: false
    horizontal chans:
    - E
    - N
    - '1'
    - '2'
    interpolate: false
    min cc: 0.3
    min cc from mean cc factor: null
    plot: false
    plotdir: null
    shift len: 0.4
    sleep interval: 10
    vertical chans:
    - Z
    ps multiplier: 0.15
    winlen: 0.4
  mag calc: null
  hyp:
    vmodel file: /vmodel.txt
    sleep interval: 10
    min stations: 5
    max rms: 1.5
  growclust:
    correlation config:
      extract len: 2.0
      highcut: 20.0
      interpolate: false
      lowcut: 1.0
      max sep: 8
      min cc: 0.2
      min link: 8
      pre pick: 0.2
      shift len: 0.2
      weight by square: false
      max event links: 500
    vmodel file: /vmodel.txt
    delmax: 80
    fout boot: NONE
    nboot: 0
    rmin: 0.3
    rmincut: 0
    rmsmax: 0.5
    rpsavgmin: 0
    tt xmax: 5000.0
    tt xmin: 0.0
    tt xstep: 1.0
    tt zmax: 500.0
    tt zmin: -4.0
    tt zstep: 1.0
    ttabsrc: nllgrid
    sleep interval: 10
  nll:
    infile: nonlinloc_files/NonLinLoc_3d.in
    veldir: nonlinloc_files
    maxdepth: 300.0
    maxlat: null
    maxlon: null
    mindepth: -3.0
    minlat: null
    minlon: null
    nodespacing: 1.0
    sleep interval: 10
    station file: stations.xml
    
    
